### ISSUE TITLE
Deadline TODO

### ISSUE THREAD

**Issue by Kryniek** [Kryniek/Russia2018WorldCupApi#25]
# **11.06.2018**

GUI:
 - [x] login view
 - [x] register view
 - [x] world cup winner view
 - [x] groups winner view
 - [x] home view //only with today matches

SRV:
- [x] register `POST - /users/` - 
- [X] login with flow - redirect to home page after login
- `POST /bets/{login}/bet` for world cup winner and groups winner functionality
- [X] matches refactor in database
- [X] `GET /matches/` && `GET /matches/{date}`
- optional, cause time is money - bets for matches on the same endpoint as above
 
# **12.06.2018**

GUI:
 - home view //only with matches view and match bet view redirect
 - matches view //with collapsible panels by date, only with match bet view redirect
 - match bet view //mayby modal ?

**Comment by bskorka** [comment]
To get data from map in Thymeleaf in groupWinners view similar construction of code is needed.

```html
<table>
    <tr th:each="groupName : ${teamsByGroupName}">
        <td th:text="${groupName.key}"/>
        <table>
            <tr th:each="teamName : ${groupName.value}">
		<td th:text="${teamName}"/>
            </tr>
	</table>
    </tr>
</table>
```
